version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php-fpm
    networks:
      - skud_network
    command: nginx -g 'daemon off;'

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./.env.prod:/var/www/.env
      - ./src:/var/www
      - ./docker/php-fpm/prod.ini:/usr/local/etc/php/conf.d/prod.ini
      - ~/.ssh:/root/.ssh:ro
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - skud_network
    command: php-fpm

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli/prod/Dockerfile
    volumes:
      - ./.env.prod:/var/www/.env
      - ./src:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - COMPOSER_MEMORY_LIMIT=-1
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - skud_network
    tty: true

  mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=laravel
      - TZ=Europe/Moscow
    restart: always
    networks:
      - skud_network
    ports:
      - "33061:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - skud_network
    volumes:
      - redis_data:/data

  go-server:
    build:
      context: ./docker/go-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
    ports:
      - "8082:8082"
    networks:
      - skud_network
    command: ["./server"]
  frp:
    image: geektr/frp
    build:
      context: .
      dockerfile: docker/frp/Dockerfile
    volumes:
      - ./docker/frp/frpc.ini:/etc/frp/frpc.ini:ro
    networks:
      - skud_network  # Используйте имя вашей основной сети
    depends_on:
      - nginx
      - mysql
volumes:
  db_data:
  redis_data:
networks:
  skud_network:
    name: skud_network
    driver: bridge